### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by Jason190** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#1]
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
  > JSR/RET are not supported with computeFrames option

**Comment by dji-dev** [comment]
Hi Jason, could you provide us with your Android device type, system version and Android Studio version to check? The GSDemo should work well with Android 6.0 Marshmallow in Android Studio 2.1.1.

**Comment by PanGuangwei** [comment]
file->setting->build...->instant run -> Do not choose the “enable instant run....”

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current sdk version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
