### ISSUE TITLE
M300定位偏移太大

### ISSUE THREAD

**Issue by dingpwen** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#10]
我们的程序差不多是按例子写的，准备去测试的时候，发现开始的定位（搜星足够的18左右）（即程序中的locate）偏移太大，差不多偏移一公里，有人说这个定位的时手机的gps，但程序中明明用的是飞机的啊：
mFlightController?.setStateCallback {  curState ->
            run {
                droneLat = curState.aircraftLocation.latitude
                droneLng = curState.aircraftLocation.longitude
                updateDroneLocation()
            }
        }

还有这种情况下做航点规划，我是该以这个定位的位置做航点规划， 还是以飞机实际所在位置做航点规划呢？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41132'>Zendesk ticket #41132</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dingpwen** [comment]
国内政策的问题。
