### ISSUE TITLE
Mavic mini waypoint

### ISSUE THREAD

**Issue by utya** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#11]
Hi..does mavic mini support waypoint? I use sdk 4.13.1
When i upload the the waypoint, i get error

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41776'>Zendesk ticket #41776</a>:<br><br>Dear Client
Thank you for contacting DJI.

Mavic Mini does not support any type of missions, eg waypointMission.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
