### ISSUE TITLE
Waypoints 2.0 Mavic 2 pro

### ISSUE THREAD

**Issue by tobratland** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#17]
Hi

Im trying to use Waypoints 2.0 with Mavic 2 pro, and im not able to getWaypointMissionv2Operator, it returns null. Any suggestions?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/47937'>Zendesk ticket #47937</a>:<br><br>Dear Client
Thank you for contacting DJI.

You should use WaypointMission, Waypoint 2.0 is designed for M300RTK.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
