### ISSUE TITLE
Mavic 2 pro gimbal yaw allways to the right

### ISSUE THREAD

**Issue by tobratland** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#18]
When starting a waypoints mission with mavic 2 pro, the yaw of the gimbal is set to the right. I am not able to programmaticaly change this during the mission. Any sugestions? Id like the gimbal yaw to be at the center during the entire flight.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48282'>Zendesk ticket #48282</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Are you testing it in a simulator?
This problem will only occur in the simulator, and will not in a real flight.
As a workaround, you can make the drone point to the true north, and the gimbal will be ok.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by tobratland** [comment]
Thank you, it was indeed the simulator.
