### ISSUE TITLE
When addListener( ) is run, a null pointer exception occurs

### ISSUE THREAD

**Issue by jiyangyang0319** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#2]
#### Is this issue about bugs or crash issues of the Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

When addListener( ) is run, a null pointer exception occurs 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'dji.sdk.mission.waypoint.WaypointMissionOperator dji.sdk.mission.MissionControl.getWaypointMissionOperator()' on a null object reference

**Comment by jiyangyang0319** [comment]
when I connect to Dji mavic,this exception is still there

**Comment by oliverou** [comment]
Hi @jiyangyang0319 , please provide the following info for us to investigate the issue:

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

Also, please make sure the DJI product has connected using the ConnectionActivity to check before you enter the MainActivity. You can also check this sample's tutorial for implementation details: [Create a MapView and Waypoint Application](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/GSDemo-Gaode-Map.html).
