### ISSUE TITLE
直接跑download下来的函数遇到语法错误。。。

### ISSUE THREAD

**Issue by caleb072350** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#5]
您好，在跑您这个程序的时候，在ConnectionActivity这个类中有一个函数startSDKRegistration，里面有个DJISDKManager.getInstance().registerApp(),第二个参数报错，原因是没有重写onIinitProgress（）函数，请问有人遇到这个问题吗？

**Comment by caleb072350** [comment]
my problem

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26836'>Zendesk ticket #26836</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。

请问您是运行的哪个版本的程序，可以看到我们最新的示例程序是有重写onIinitProgress（）这个函数的。如果您下载的示例中onIinitProgress（）没有重写，您按照下图的方法重写一下即可，该函数没有实现具体功能。
 ![](https://djisdksupport.zendesk.com/attachments/token/lw6fZSsUsCYRiBRKFyftf8MCd/?name=inline227368704.png)​

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/lw6fZSsUsCYRiBRKFyftf8MCd' target='zd_attach'>inline227368704.png</a>

**Comment by caleb072350** [comment]
哦哦，是我的问题，现在已经解决了，谢谢
