### ISSUE TITLE
跑这个代码的时候遇到一些类找不到，请问怎么办啊？

### ISSUE THREAD

**Issue by caleb072350** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#6]
import com.amap.api.maps2d.AMap;
import com.amap.api.maps2d.AMap.OnMapClickListener;
import com.amap.api.maps2d.CameraUpdate;
import com.amap.api.maps2d.CameraUpdateFactory;
import com.amap.api.maps2d.MapView;
import com.amap.api.maps2d.model.BitmapDescriptorFactory;
import com.amap.api.maps2d.model.LatLng;
import com.amap.api.maps2d.model.Marker;
import com.amap.api.maps2d.model.MarkerOptions;

报错maps2d找不到。。。请问您这个代码可以直接跑通吗？还是需要配置环境变量，有的话请告知，谢谢

**Comment by caleb072350** [comment]
我用的Android Studio3.0.1，Android SDK版本是26，完全按照教程来的，但是代码跑不通

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/26880'>Zendesk ticket #26880</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
这边测试示例代码是没有问题的，建议您确认下是否正常编译成功示例代码。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by rangerzhou** [comment]
请教下有没有输入经纬度飞行的 API？
