### ISSUE TITLE
reach point trigger can not match AircraftControl actuator

### ISSUE THREAD

**Issue by 72chen** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#7]

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/35470'>Zendesk ticket #35470</a>:<br><br>Dear Client
Thank you for contacting DJI.

Hi, are you using WaypointV2Mission? It is only supported by M300. Could you clarify your problem please. How the REACH_POINT trigger cannnot match with AIRCRAFT_CONTROL actuator.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by 72chen** [comment]
After update the firmware of RemoteController ,the problem was resolved.
