### ISSUE TITLE
Waypoint 2.0 support

### ISSUE THREAD

**Issue by brien-crean** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-Gaode-Map#8]
I tried to use this sample application to test the new capabilities of Waypoint 2.0. I can't seem to find anywhere in the SDK documentation or in the release notes as to which drones support WaypointV2. Is there a list somewhere that I am missing?

I tried with a Mavic Pro 2 running the latest firmware on SDK v4.12 and I get "Not support Waypoint2.0"

**EDIT:** I just noticed a closed issue on this repo mentions WaypointV2 is only supported by M300. **Is WaypointV2 only supported by the M300?**

**Comment by dji-dev** [comment]
Agent comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/35980'>Zendesk ticket #35980</a>:<br><br>Currently only the M300 supports Waypoint 2.0: https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointV2Mission.html

Lisa Fedane
DJI Developer Support Team - US

Join DJI's Developer Community in our new Forum for Technical Discussions, Announcements and More:
https://forum.dji.com/forum-139-1.html?from=developer

**Comment by brien-crean** [comment]
Thanks for letting me know
